### ISSUE TITLE
bytes_stored is broken when --nodes are passed

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/elasticsearch-drain#20]
When you pass `nodes` the search for `bytes_stored` is broken.

```
/Users/athompson/code/personal/elasticsearch-drain/lib/elasticsearch/drain/cli.rb:80:in `block in remove_nodes': undefined method `bytes_stored' for nil:NilClass (NoMethodError)
    from /Users/athompson/code/personal/elasticsearch-drain/lib/elasticsearch/drain/cli.rb:78:in `each'
    from /Users/athompson/code/personal/elasticsearch-drain/lib/elasticsearch/drain/cli.rb:78:in `remove_nodes'
    from /Users/athompson/code/personal/elasticsearch-drain/lib/elasticsearch/drain/cli.rb:33:in `asg'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/athompson/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from bin/drain:3:in `<main>'
```

This feature was introduced in #18

**Comment by dgreene-r7** [comment]
This is fixed by #23.
